[2022-12-15T06:02:27.681+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_data_mart.artist_produktif manual__2022-12-15T04:11:54.851204+00:00 [queued]>
[2022-12-15T06:02:27.704+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_data_mart.artist_produktif manual__2022-12-15T04:11:54.851204+00:00 [queued]>
[2022-12-15T06:02:27.705+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T06:02:27.705+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 4
[2022-12-15T06:02:27.706+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T06:02:27.755+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): artist_produktif> on 2022-12-15 04:11:54.851204+00:00
[2022-12-15T06:02:27.763+0000] {standard_task_runner.py:55} INFO - Started process 4388 to run task
[2022-12-15T06:02:27.770+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_data_mart', 'artist_produktif', 'manual__2022-12-15T04:11:54.851204+00:00', '--job-id', '561', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_mart.py', '--cfg-path', '/tmp/tmps3cqu1z3']
[2022-12-15T06:02:27.774+0000] {standard_task_runner.py:83} INFO - Job 561: Subtask artist_produktif
[2022-12-15T06:02:27.888+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_data_mart.artist_produktif manual__2022-12-15T04:11:54.851204+00:00 [running]> on host 0d7510ca55af
[2022-12-15T06:02:28.023+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_data_mart
AIRFLOW_CTX_TASK_ID=artist_produktif
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T04:11:54.851204+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-15T04:11:54.851204+00:00
[2022-12-15T06:02:39.614+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/data_mart.py", line 70, in artist_produktif
    make_data(query, 'artist_produktif')
  File "/opt/airflow/plugins/data_mart.py", line 26, in make_data
    print(job.result().rows)
AttributeError: 'LoadJob' object has no attribute 'rows'
[2022-12-15T06:02:39.633+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag_data_mart, task_id=artist_produktif, execution_date=20221215T041154, start_date=20221215T060227, end_date=20221215T060239
[2022-12-15T06:02:39.665+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 561 for task artist_produktif ('LoadJob' object has no attribute 'rows'; 4388)
[2022-12-15T06:02:39.722+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-15T06:02:39.765+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
